// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/item/item.proto

package item

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_proto_item_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_item_proto_rawDescGZIP(), []int{0}
}

func (x *GetInventoryRequest) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type ItemStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId    int32                  `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Info          string                 `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemStruct) Reset() {
	*x = ItemStruct{}
	mi := &file_proto_item_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemStruct) ProtoMessage() {}

func (x *ItemStruct) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemStruct.ProtoReflect.Descriptor instead.
func (*ItemStruct) Descriptor() ([]byte, []int) {
	return file_proto_item_item_proto_rawDescGZIP(), []int{1}
}

func (x *ItemStruct) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemStruct) GetTemplateId() int32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *ItemStruct) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ItemStruct) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type GetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ItemStruct          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_proto_item_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_item_item_proto_rawDescGZIP(), []int{2}
}

func (x *GetInventoryResponse) GetItems() []*ItemStruct {
	if x != nil {
		return x.Items
	}
	return nil
}

type UseItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // Inventory index or unique ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemRequest) Reset() {
	*x = UseItemRequest{}
	mi := &file_proto_item_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemRequest) ProtoMessage() {}

func (x *UseItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemRequest.ProtoReflect.Descriptor instead.
func (*UseItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_item_item_proto_rawDescGZIP(), []int{3}
}

func (x *UseItemRequest) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *UseItemRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type UseItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemResponse) Reset() {
	*x = UseItemResponse{}
	mi := &file_proto_item_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemResponse) ProtoMessage() {}

func (x *UseItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_item_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemResponse.ProtoReflect.Descriptor instead.
func (*UseItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_item_item_proto_rawDescGZIP(), []int{4}
}

func (x *UseItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UseItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_item_item_proto protoreflect.FileDescriptor

const file_proto_item_item_proto_rawDesc = "" +
	"\n" +
	"\x15proto/item/item.proto\x12\x04item\"2\n" +
	"\x13GetInventoryRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\"m\n" +
	"\n" +
	"ItemStruct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x05R\n" +
	"templateId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04info\x18\x04 \x01(\tR\x04info\">\n" +
	"\x14GetInventoryResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.item.ItemStructR\x05items\"F\n" +
	"\x0eUseItemRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\"E\n" +
	"\x0fUseItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8c\x01\n" +
	"\vItemService\x12E\n" +
	"\fGetInventory\x12\x19.item.GetInventoryRequest\x1a\x1a.item.GetInventoryResponse\x126\n" +
	"\aUseItem\x12\x14.item.UseItemRequest\x1a\x15.item.UseItemResponseB\x10Z\x0enro-go/pb/itemb\x06proto3"

var (
	file_proto_item_item_proto_rawDescOnce sync.Once
	file_proto_item_item_proto_rawDescData []byte
)

func file_proto_item_item_proto_rawDescGZIP() []byte {
	file_proto_item_item_proto_rawDescOnce.Do(func() {
		file_proto_item_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_item_item_proto_rawDesc), len(file_proto_item_item_proto_rawDesc)))
	})
	return file_proto_item_item_proto_rawDescData
}

var file_proto_item_item_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_item_item_proto_goTypes = []any{
	(*GetInventoryRequest)(nil),  // 0: item.GetInventoryRequest
	(*ItemStruct)(nil),           // 1: item.ItemStruct
	(*GetInventoryResponse)(nil), // 2: item.GetInventoryResponse
	(*UseItemRequest)(nil),       // 3: item.UseItemRequest
	(*UseItemResponse)(nil),      // 4: item.UseItemResponse
}
var file_proto_item_item_proto_depIdxs = []int32{
	1, // 0: item.GetInventoryResponse.items:type_name -> item.ItemStruct
	0, // 1: item.ItemService.GetInventory:input_type -> item.GetInventoryRequest
	3, // 2: item.ItemService.UseItem:input_type -> item.UseItemRequest
	2, // 3: item.ItemService.GetInventory:output_type -> item.GetInventoryResponse
	4, // 4: item.ItemService.UseItem:output_type -> item.UseItemResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_item_item_proto_init() }
func file_proto_item_item_proto_init() {
	if File_proto_item_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_item_item_proto_rawDesc), len(file_proto_item_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_item_item_proto_goTypes,
		DependencyIndexes: file_proto_item_item_proto_depIdxs,
		MessageInfos:      file_proto_item_item_proto_msgTypes,
	}.Build()
	File_proto_item_item_proto = out.File
	file_proto_item_item_proto_goTypes = nil
	file_proto_item_item_proto_depIdxs = nil
}
