// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/world/world.proto

package world

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlayerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerInfoRequest) Reset() {
	*x = GetPlayerInfoRequest{}
	mi := &file_proto_world_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoRequest) ProtoMessage() {}

func (x *GetPlayerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlayerInfoRequest) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GetPlayerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hp            int64                  `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int64                  `protobuf:"varint,4,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	MapId         int32                  `protobuf:"varint,5,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	ZoneId        int32                  `protobuf:"varint,6,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	X             int32                  `protobuf:"varint,7,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,8,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerInfoResponse) Reset() {
	*x = GetPlayerInfoResponse{}
	mi := &file_proto_world_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoResponse) ProtoMessage() {}

func (x *GetPlayerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayerInfoResponse) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GetPlayerInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetPlayerInfoResponse) GetHp() int64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *GetPlayerInfoResponse) GetMaxHp() int64 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *GetPlayerInfoResponse) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *GetPlayerInfoResponse) GetZoneId() int32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *GetPlayerInfoResponse) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GetPlayerInfoResponse) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type UpdatePlayerPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MapId         int32                  `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	ZoneId        int32                  `protobuf:"varint,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	X             int32                  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerPositionRequest) Reset() {
	*x = UpdatePlayerPositionRequest{}
	mi := &file_proto_world_world_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerPositionRequest) ProtoMessage() {}

func (x *UpdatePlayerPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerPositionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerPositionRequest) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePlayerPositionRequest) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *UpdatePlayerPositionRequest) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *UpdatePlayerPositionRequest) GetZoneId() int32 {
	if x != nil {
		return x.ZoneId
	}
	return 0
}

func (x *UpdatePlayerPositionRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *UpdatePlayerPositionRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type UpdatePlayerPositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerPositionResponse) Reset() {
	*x = UpdatePlayerPositionResponse{}
	mi := &file_proto_world_world_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerPositionResponse) ProtoMessage() {}

func (x *UpdatePlayerPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_world_world_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerPositionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlayerPositionResponse) Descriptor() ([]byte, []int) {
	return file_proto_world_world_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePlayerPositionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_world_world_proto protoreflect.FileDescriptor

const file_proto_world_world_proto_rawDesc = "" +
	"\n" +
	"\x17proto/world/world.proto\x12\x05world\"3\n" +
	"\x14GetPlayerInfoRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\"\xbb\x01\n" +
	"\x15GetPlayerInfoResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02hp\x18\x03 \x01(\x03R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x04 \x01(\x03R\x05maxHp\x12\x15\n" +
	"\x06map_id\x18\x05 \x01(\x05R\x05mapId\x12\x17\n" +
	"\azone_id\x18\x06 \x01(\x05R\x06zoneId\x12\f\n" +
	"\x01x\x18\a \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\b \x01(\x05R\x01y\"\x86\x01\n" +
	"\x1bUpdatePlayerPositionRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\x05R\x05mapId\x12\x17\n" +
	"\azone_id\x18\x03 \x01(\x05R\x06zoneId\x12\f\n" +
	"\x01x\x18\x04 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x05R\x01y\"8\n" +
	"\x1cUpdatePlayerPositionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xbb\x01\n" +
	"\fWorldService\x12J\n" +
	"\rGetPlayerInfo\x12\x1b.world.GetPlayerInfoRequest\x1a\x1c.world.GetPlayerInfoResponse\x12_\n" +
	"\x14UpdatePlayerPosition\x12\".world.UpdatePlayerPositionRequest\x1a#.world.UpdatePlayerPositionResponseB\x11Z\x0fnro-go/pb/worldb\x06proto3"

var (
	file_proto_world_world_proto_rawDescOnce sync.Once
	file_proto_world_world_proto_rawDescData []byte
)

func file_proto_world_world_proto_rawDescGZIP() []byte {
	file_proto_world_world_proto_rawDescOnce.Do(func() {
		file_proto_world_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_world_world_proto_rawDesc), len(file_proto_world_world_proto_rawDesc)))
	})
	return file_proto_world_world_proto_rawDescData
}

var file_proto_world_world_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_world_world_proto_goTypes = []any{
	(*GetPlayerInfoRequest)(nil),         // 0: world.GetPlayerInfoRequest
	(*GetPlayerInfoResponse)(nil),        // 1: world.GetPlayerInfoResponse
	(*UpdatePlayerPositionRequest)(nil),  // 2: world.UpdatePlayerPositionRequest
	(*UpdatePlayerPositionResponse)(nil), // 3: world.UpdatePlayerPositionResponse
}
var file_proto_world_world_proto_depIdxs = []int32{
	0, // 0: world.WorldService.GetPlayerInfo:input_type -> world.GetPlayerInfoRequest
	2, // 1: world.WorldService.UpdatePlayerPosition:input_type -> world.UpdatePlayerPositionRequest
	1, // 2: world.WorldService.GetPlayerInfo:output_type -> world.GetPlayerInfoResponse
	3, // 3: world.WorldService.UpdatePlayerPosition:output_type -> world.UpdatePlayerPositionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_world_world_proto_init() }
func file_proto_world_world_proto_init() {
	if File_proto_world_world_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_world_world_proto_rawDesc), len(file_proto_world_world_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_world_world_proto_goTypes,
		DependencyIndexes: file_proto_world_world_proto_depIdxs,
		MessageInfos:      file_proto_world_world_proto_msgTypes,
	}.Build()
	File_proto_world_world_proto = out.File
	file_proto_world_world_proto_goTypes = nil
	file_proto_world_world_proto_depIdxs = nil
}
